#include "hal_data.h"
#include "Uart9_Debug.h"
#include "board_sdram.h"
#include "mipi_dsi_ep.h"
#include "Stepping_Motor.h"
#include "stdio.h"
#include "ov5640.h"
#include "ceu.h"
#include "gt911.h"
#include "graphics.h"
#include "common_data.h"
#include "string.h"
#include "models/model.h"
#include "ai_preprocess.h"
#include "ai_postprocess.h"
#include "ai_center_offset.h"
#include "robot_arm.h"
#include "bottom_banner.h"
#include "harvest_task.h"
#include "ui_control.h"
#include "Asrpro.h"

#if (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
bsp_ipc_semaphore_handle_t g_core_start_semaphore =
{
    .semaphore_num = 0
};
#endif

#define CAMERA_FRAME_BYTES   (VGA_WIDTH * VGA_HEIGHT * RGB565_BYTE_PER_PIXEL)
#define AI_RESULT_HOLD_FRAMES   (2U)

/*
 * 相机双缓存放�?cacheable SDRAM�? * CEU 写下一帧时，CPU/NPU 可以同时处理上一帧；
 * 每次重新启动采集前先�?DCache 失效，避�?CPU 读到旧图�? */
uint8_t g_image_vga_sdram[2][CAMERA_FRAME_BYTES]
    BSP_PLACE_IN_SECTION(".sdram") BSP_ALIGN_VARIABLE(32);

static void prepare_camera_capture_buffer(uint8_t * p_buffer)
{
    SCB_CleanInvalidateDCache_by_Addr(p_buffer, (int32_t) CAMERA_FRAME_BYTES);
    __DSB();
    __ISB();
}


static bool wait_vsync_with_timeout(uint32_t timeout_ms)
{
    uint32_t waited_ms = 0U;
    while (!g_vsync_flag)
    {
        R_BSP_SoftwareDelay(1, BSP_DELAY_UNITS_MILLISECONDS);
        waited_ms++;
        if (waited_ms >= timeout_ms)
        {
            DBG_LOG("[VSYNC] timeout after %lu ms\r\n", (unsigned long) timeout_ms);
            return false;
        }
    }

    return true;
}

extern void DWT_init(void);
extern uint32_t DWT_get_count(void);
extern uint32_t DWT_count_to_us(uint32_t delta_count);

#define PIPELINE_PROFILE_PRINT_INTERVAL    (30U)

typedef struct st_pipeline_profile
{
    uint32_t ceu_us;
    uint32_t ceu_kick_us;
    uint32_t vsync_wait_us;
    uint32_t blit_us;
    uint32_t draw_us;
    uint32_t preprocess_us;
    uint32_t model_us;
    uint32_t cpu_us;
    uint32_t npu_us;
    uint32_t post_us;
    uint32_t center_us;
    uint32_t total_us;
} pipeline_profile_t;

static uint32_t pipeline_profile_measure_begin(void)
{
    return DWT_get_count();
}

static uint32_t pipeline_profile_measure_end(uint32_t start_count)
{
    return DWT_count_to_us((uint32_t) (DWT_get_count() - start_count));
}

static void pipeline_profile_print_every(const pipeline_profile_t * p_profile)
{
    static uint32_t s_frame_count = 0U;

    s_frame_count++;
    if ((1U == s_frame_count) || (0U == (s_frame_count % PIPELINE_PROFILE_PRINT_INTERVAL)))
    {
        uint32_t fps_x100 = (p_profile->total_us > 0U) ? (100000000U / p_profile->total_us) : 0U;
        uint32_t fps_int   = fps_x100 / 100U;
        uint32_t fps_frac  = fps_x100 % 100U;

        /* CEU 事件计数（诊断：帧率劣化是 error 风暴还是断流） */
        extern volatile uint32_t g_ceu_frame_end_count;
        extern volatile uint32_t g_ceu_error_count;
        extern volatile uint32_t g_ceu_callback_count;
        extern volatile uint32_t g_ceu_sync_event_count;

        DBG_LOG("[PIPE] frame=%lu fps=%lu.%02lu total=%lu us ceu_wait=%lu us ceu_kick=%lu us vsync=%lu us blit=%lu us draw=%lu us pre=%lu us model=%lu us post=%lu us center=%lu us ceu_fe=%lu ceu_err=%lu ceu_cb=%lu ceu_sync=%lu\r\n",
               (unsigned long) s_frame_count,
               (unsigned long) fps_int,
               (unsigned long) fps_frac,
               (unsigned long) p_profile->total_us,
               (unsigned long) p_profile->ceu_us,
               (unsigned long) p_profile->ceu_kick_us,
               (unsigned long) p_profile->vsync_wait_us,
               (unsigned long) p_profile->blit_us,
               (unsigned long) p_profile->draw_us,
               (unsigned long) p_profile->preprocess_us,
               (unsigned long) p_profile->model_us,
               (unsigned long) p_profile->post_us,
               (unsigned long) p_profile->center_us,
               (unsigned long) g_ceu_frame_end_count,
               (unsigned long) g_ceu_error_count,
               (unsigned long) g_ceu_callback_count,
               (unsigned long) g_ceu_sync_event_count);
    }
}

void g_timer_servo_tick_callback(timer_callback_args_t *p_args)
{
    FSP_PARAMETER_NOT_USED(p_args);
    RobotArm_Update();
}

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    // SDRAM is initialized in warmstart by R_BSP_SdramInit(true).
    /* TODO: add your own code here */
    uint32_t  ceu_used;
    fsp_err_t err = FSP_SUCCESS;
    fsp_err_t ioport_err = R_IOPORT_Open(&g_ioport_ctrl, &g_bsp_pin_cfg1);
    if (FSP_ERR_ALREADY_OPEN == ioport_err)
    {
        ioport_err = R_IOPORT_PinsCfg(&g_ioport_ctrl, &g_bsp_pin_cfg1);
    }

    uart9_Init();
    DBG_LOG("test\r\n");

    RobotArm_Init();
    err = g_timer_servo_tick.p_api->open(g_timer_servo_tick.p_ctrl, g_timer_servo_tick.p_cfg);
    if (FSP_SUCCESS != err)
    {
        DBG_LOG("Servo tick timer open failed: %d\r\n", (int) err);
    }
    else
    {
        err = g_timer_servo_tick.p_api->start(g_timer_servo_tick.p_ctrl);
        if (FSP_SUCCESS != err)
        {
            DBG_LOG("Servo tick timer start failed: %d\r\n", (int) err);
        }
    }

    graphics_init(); // Initialize Dave2D graphics engine.
    mipi_dsi_entry();
    st7123_touch_irq_init();
    ui_control_init(); // 手绘双界面 UI：品牌条 + banner + MODE/START 按钮
    ASRPRO_Init();     // 语音模块初始化
    __DSB();

    DWT_init();   /* 提前使能 DWT 周期计数器：spinner 时间节流依赖（无副作用） */
    R_IIC_MASTER_Open(&g_i2c_master0_ctrl, &g_i2c_master0_cfg); // I2C for camera and touch panel.
    ui_control_draw_boot_text("正在初始化");   /* 上电提示：OV5640 配置 ~1s */
    ov5640_init();
    ov5640_config_dvp_vga_rgb565_15fps();
//    ov5640_set_output_format(OV5640_OUTPUT_FORMAT_RGB565);
//    ov5640_set_output_size(VGA_WIDTH,VGA_HEIGHT);
    ov5640_auto_focus_init();
    ov5640_set_exposure_level(OV5640_EXPOSURE_LEVEL_5);

    ceu_init(g_image_vga_sdram[0], VGA_WIDTH, VGA_HEIGHT);
    /* ===== NPU init ===== */

    ui_control_draw_boot_text("正在初始化");      /* 上电提示：Ethos-U55 初始化 */
    /* NPU Open 是单条阻塞调用，无法内插 tick；仅前后各补 1 帧让 spinner 过渡，
     * 不加长延时（不拖慢相机画面出现）。 */
    ui_control_draw_boot_text("正在初始化");
    R_BSP_SoftwareDelay(30U, BSP_DELAY_UNITS_MILLISECONDS);
    err  = RM_ETHOSU_Open(&g_rm_ethosu0_ctrl, &g_rm_ethosu0_cfg);
    ui_control_draw_boot_text("正在初始化");
    R_BSP_SoftwareDelay(30U, BSP_DELAY_UNITS_MILLISECONDS);
    if (FSP_SUCCESS != err)
    {
        DBG_LOG("NPU Ethos-U55 open failed: %d\r\n", err);
    }
    else
    {
        DBG_LOG("NPU Ethos-U55 initialized successfully\r\n");
    }

    /*
     * 当前 AI 主链路：
     * 1) CEU 采集到双缓冲
     * 2) 对最新完整帧做预处理
     * 3) �?TFLite int8 + Ethos-U55
     * 4) 后处理后保留检测结果，画框和中心偏移给机械臂用
     */
    ai_letterbox_info_t letterbox_info;
    ai_detection_t detections_work[AI_POST_MAX_DETECT];
    ai_detection_t detections_committed[AI_POST_MAX_DETECT];
    uint32_t num_detections_work = 0U;
    uint32_t num_detections_committed = 0U;
    uint32_t detection_hold_frames = 0U;
    uint8_t * p_camera_buffers[2] = { g_image_vga_sdram[0], g_image_vga_sdram[1] };
    uint32_t frame_index_display = 0U;
    uint32_t frame_index_capture = 1U;
    uint32_t s_last_frame_cyc = 0U;   /* 最近一次相机帧处理时刻（DWT，断流检测，2s） */
    uint32_t s_prev_frame_end_cyc = 0U;  /* 上一帧处理完成时的 DWT 周期（真实帧率测量） */
    int8_t *p_model_input = GetModelInputPtr_serving_default_images_0();
    int8_t *p_model_p4    = GetModelOutputPtr_PartitionedCall_0_70298();
    int8_t *p_model_p5    = GetModelOutputPtr_PartitionedCall_1_70299();
    DBG_LOG("[MODEL] profiling enabled on UART9; backend=tflite-int8(cpu+npu)\r\n");
    /* 上电不启动抓取：等待用户在屏幕上按 POWER 开关后，由 ui_control 启动
     * HarvestTask_Init()。 */
    prepare_camera_capture_buffer(p_camera_buffers[frame_index_display]);
    err = ceu_capture_start(p_camera_buffers[frame_index_display]);
    if (FSP_SUCCESS != err)
    {
        DBG_LOG("CEU initial capture start failed: %d\r\n", (int) err);
        return;
    }
    /* 中断级 kick：告知回调当前采集缓冲（此后每帧 FRAME_END 由回调直接 kick 下一帧） */
    ceu_set_capture_buf(p_camera_buffers[frame_index_display]);

    /* 首帧等待：5s 超时后重试一次 kick+wait，仍失败则继续进主循环（断流自愈兜底）。
     * 绝不 return——return 后主循环不跑，系统卡死无画面。 */
    err = ceu_capture_wait(&ceu_used, 5000U);
    if (FSP_SUCCESS != err)
    {
        DBG_LOG("CEU initial wait: %d, retry capture\r\n", (int) err);
        prepare_camera_capture_buffer(p_camera_buffers[frame_index_display]);
        err = ceu_capture_start(p_camera_buffers[frame_index_display]);
        if (FSP_SUCCESS != err)
        {
            DBG_LOG("CEU initial kick failed: %d\r\n", (int) err);
        }
        err = ceu_capture_wait(&ceu_used, 5000U);
        if (FSP_SUCCESS != err)
        {
            DBG_LOG("CEU initial wait retry failed: %d, continue to main loop\r\n", (int) err);
        }
    }

    /*
     * Pipeline:
     * 1) Display/process the latest completed frame.
     * 2) Capture the next frame into the other SDRAM buffer in parallel.
     */
    while(1)
    {
          /* 高频触摸 + UI 状态机（摇杆/按钮）：每轮执行，vsync 60Hz 节奏，
           * 不受相机 8fps 限制——遥控操作流畅跟手 */
          st7123_touch_irq_print_task();
          ui_control_service();
          ASRPRO_Process();  /* 语音命令处理 */

          /* 非阻塞轮询相机帧完成（CEU 回调置 g_capture_ready） */
          if (g_capture_ready)
          {
              g_capture_ready = false;
              s_last_frame_cyc = DWT_get_count();

          pipeline_profile_t pipe_profile = {0};
          uint32_t stage_start = 0U;
          /* 帧周期计时：纯帧间隔 = 本帧开始 - 上一帧开始（不含本帧处理时间，
           * 中断级 kick 流水线真实出帧率 7.2fps；含处理会显示 5.15 误导） */
          uint32_t now_cyc = DWT_get_count();
          uint32_t loop_start = (0U != s_prev_frame_end_cyc) ? s_prev_frame_end_cyc : now_cyc;
          s_prev_frame_end_cyc = now_cyc;
          uint32_t frame_period_us = DWT_count_to_us(now_cyc - loop_start);
          const model_profile_t * p_model_profile = NULL;
          /* 中断级 kick 流水线：帧由 CEU 回调（FRAME_END）采完并直接 kick 下一帧，
           * 主循环只处理 g_ceu_completed_buf（刚采完的帧） */
          uint8_t * p_display_frame = (uint8_t *) g_ceu_completed_buf;

          /* 处理前 Invalidate：丢弃缓存旧行，读 CEU DMA 刚写入的新帧（SDRAM） */
          stage_start = pipeline_profile_measure_begin();
          SCB_InvalidateDCache_by_Addr(p_display_frame, (int32_t) CAMERA_FRAME_BYTES);
          __DSB();
          __ISB();
          pipe_profile.ceu_kick_us = pipeline_profile_measure_end(stage_start);

          /* Dave2D hardware scale: 640x480 -> camera window on display.
           * AUTO: full 480x612 (y28-640) split into regions that skip MODE/START
           * button rects -> buttons are never covered by camera frame (no flicker).
           * REMOTE: single 480x360 top window. */
          int cam_x, cam_y, cam_w, cam_h;
          bool is_auto = ui_control_get_camera_rect(&cam_x, &cam_y, &cam_w, &cam_h);
          stage_start = pipeline_profile_measure_begin();
          if (is_auto)
          {
                          /* 目标带 y0-600（600 行）↔ 源 640x480：x 0.75, y 1.25。
               * y600-640 为控制条（模式/开始/灯光 同排）：整行跳过不显示相机，
               * 按钮不被相机帧覆盖 -> 零闪。 */
              const int fb_w = 480, fb_h = 800;
              uint8_t * fb = gp_frame_buffer;
              graphics_blit_scale_region(p_display_frame, 640, 480, 0, 0, 640, 480,
                  fb, (int)g_hstride, fb_w, fb_h, 0, 0, 480, 600);
          }
          else
          {
              graphics_blit_scale(p_display_frame, 640, 480,
                      (uint8_t *) gp_frame_buffer + (uint32_t) cam_y * g_hstride * 2U,
                                  cam_w, cam_h,
                                  (int)g_hstride);
          }
          pipe_profile.blit_us = pipeline_profile_measure_end(stage_start);

          /* 画框使用已提交结果；仅 AUTO 界面画（REMOTE 画面缩小，坐标系不匹配） */
          stage_start = pipeline_profile_measure_begin();
          if (is_auto)
          {
              ai_draw_detections(detections_committed, num_detections_committed);
          }
          ui_control_set_detection_count(num_detections_committed);
          pipe_profile.draw_us = pipeline_profile_measure_end(stage_start);
          __DSB();

          /* blit 覆盖了品牌条/按钮：立即重绘浮层（覆盖瞬间恢复，防闪烁） */
          ui_control_draw_overlay();


          /* AI 推理仅 AUTO 模式执行（REMOTE 跳过，保证摇杆响应流畅） */
          if (is_auto)
          {
              stage_start = pipeline_profile_measure_begin();
              ai_preprocess_rgb565(p_display_frame, VGA_WIDTH, VGA_HEIGHT,
                                   p_model_input, &letterbox_info);
              pipe_profile.preprocess_us = pipeline_profile_measure_end(stage_start);

              p_model_profile = RunModelProfiled(false);
              if (NULL != p_model_profile)
              {
                  pipe_profile.model_us = p_model_profile->total_us;
                  pipe_profile.cpu_us   = p_model_profile->cpu_us;
                  pipe_profile.npu_us   = p_model_profile->npu_us;
              }

              num_detections_work = 0U;
              stage_start = pipeline_profile_measure_begin();
              ai_postprocess(p_model_p4, p_model_p5,
                             &letterbox_info, detections_work, AI_POST_MAX_DETECT,
                             &num_detections_work);
              pipe_profile.post_us = pipeline_profile_measure_end(stage_start);

              if (num_detections_work > 0U)
              {
                  memcpy(detections_committed,
                         detections_work,
                         num_detections_work * sizeof(ai_detection_t));
                  num_detections_committed = num_detections_work;
                  detection_hold_frames = AI_RESULT_HOLD_FRAMES;
              }
              else if (detection_hold_frames > 0U)
              {
                  detection_hold_frames--;
              }
              else
              {
                  num_detections_committed = 0U;
              }
          }

          /* 中心偏移只看当前稳定结果；仅 AUTO + POWER 时驱动抓取流程 */
          stage_start = pipeline_profile_measure_begin();
          if ((UI_MODE_AUTO == ui_control_get_mode()) &&
              (UI_POWER_ON == ui_control_get_power()))
          {
              HarvestTask_Service(detections_committed, num_detections_committed);
          }
          pipe_profile.center_us = pipeline_profile_measure_end(stage_start);

          pipe_profile.total_us = frame_period_us;   /* 纯帧间隔（真实画面帧率） */
          pipeline_profile_print_every(&pipe_profile);
          }
          /* 断流自愈：距上次"帧或 recover"≥2s 才触发。首帧前 s_last_frame_cyc=0
           * 首次会立即触发（recover 救活启动期 CEU），recover 重置计时 → 限速 2s/次，
           * 不再每轮（<1ms）疯狂触发刷屏 */
          else if (DWT_count_to_us(DWT_get_count() - s_last_frame_cyc) >= 2000000U)
          {
              s_last_frame_cyc = DWT_get_count();   /* 重置计时：限速 recover */
              ceu_recover();
              /* reopen 后 CEU 空闲：直接重新 kick（回调会切换到另一块缓冲） */
              prepare_camera_capture_buffer(g_image_vga_sdram[0]);
              err = ceu_capture_start(g_image_vga_sdram[0]);
              if (FSP_SUCCESS != err)
              {
                  DBG_LOG("CEU recover kick failed: %d\r\n", (int) err);
              }
              ceu_set_capture_buf(g_image_vga_sdram[0]);
          }

          /* UI 浮层重绘：DWT 节流 ~15ms。原 wait_vsync 阻塞等 60Hz（每轮 16.7ms 粒度）
           * 导致相机 kick 延迟 0-16.7ms，总错过传感器 VSYNC → CEU 隔帧采集、
           * 帧率减半（实测 7.2 -> 3.15fps）。去掉阻塞等待后主循环自由轮询 <1ms，
           * kick 延迟 <1ms，赶上 VSYNC 帧率恢复。触摸为 INT 驱动，不受影响。 */
          static uint32_t s_last_overlay_cyc = 0U;
          uint32_t now_cyc = DWT_get_count();
          if (DWT_count_to_us(now_cyc - s_last_overlay_cyc) >= 8000U)
          {
              s_last_overlay_cyc = now_cyc;
              ui_control_draw_overlay();
          }
          __DSB();
    }

    /* Wake up 2nd core if this is first core and we are inside a multicore project. */
#if (0 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && !BSP_TZ_NONSECURE_BUILD

#if BSP_TZ_SECURE_BUILD
    /* Take semaphore so 2nd core can clear it */
    R_BSP_IpcSemaphoreTake(&g_core_start_semaphore);
#endif

    R_BSP_SecondaryCoreStart();

#if BSP_TZ_SECURE_BUILD
    /* Wait for 2nd core to start and clear semaphore */
    while(FSP_ERR_IN_USE == R_BSP_IpcSemaphoreTake(&g_core_start_semaphore))
    {
        ;
    }
#endif
#endif

#if (1 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
    /* Signal to 1st core that 2nd core has started */
    R_BSP_IpcSemaphoreGive(&g_core_start_semaphore);
#endif

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
