#include "hal_data.h"
#include "Uart9_Debug.h"
#include "board_sdram.h"
#include "mipi_dsi_ep.h"
#include "Stepping_Motor.h"
#include "stdio.h"
#include "ov5640.h"
#include "ceu.h"
#include "gt911.h"
#include "graphics.h"
#include "common_data.h"
#include "string.h"
#include "models/model.h"
#include "ai_preprocess.h"
#include "ai_postprocess.h"
#include "ai_center_offset.h"
#include "robot_arm.h"
#include "bottom_banner.h"
#include "harvest_task.h"
#include "ui_control.h"

#if (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
bsp_ipc_semaphore_handle_t g_core_start_semaphore =
{
    .semaphore_num = 0
};
#endif

#define CAMERA_FRAME_BYTES   (VGA_WIDTH * VGA_HEIGHT * RGB565_BYTE_PER_PIXEL)
#define AI_RESULT_HOLD_FRAMES   (2U)

/*
 * 相机双缓存放�?cacheable SDRAM�? * CEU 写下一帧时，CPU/NPU 可以同时处理上一帧；
 * 每次重新启动采集前先�?DCache 失效，避�?CPU 读到旧图�? */
uint8_t g_image_vga_sdram[2][CAMERA_FRAME_BYTES]
    BSP_PLACE_IN_SECTION(".sdram") BSP_ALIGN_VARIABLE(32);

static void prepare_camera_capture_buffer(uint8_t * p_buffer)
{
    SCB_CleanInvalidateDCache_by_Addr(p_buffer, (int32_t) CAMERA_FRAME_BYTES);
    __DSB();
    __ISB();
}


static bool wait_vsync_with_timeout(uint32_t timeout_ms)
{
    uint32_t waited_ms = 0U;
    while (!g_vsync_flag)
    {
        R_BSP_SoftwareDelay(1, BSP_DELAY_UNITS_MILLISECONDS);
        waited_ms++;
        if (waited_ms >= timeout_ms)
        {
            printf("[VSYNC] timeout after %lu ms\r\n", (unsigned long) timeout_ms);
            return false;
        }
    }

    return true;
}

extern void DWT_init(void);
extern uint32_t DWT_get_count(void);
extern uint32_t DWT_count_to_us(uint32_t delta_count);

#define PIPELINE_PROFILE_PRINT_INTERVAL    (30U)

typedef struct st_pipeline_profile
{
    uint32_t ceu_us;
    uint32_t ceu_kick_us;
    uint32_t vsync_wait_us;
    uint32_t blit_us;
    uint32_t draw_us;
    uint32_t preprocess_us;
    uint32_t model_us;
    uint32_t cpu_us;
    uint32_t npu_us;
    uint32_t post_us;
    uint32_t center_us;
    uint32_t total_us;
} pipeline_profile_t;

static uint32_t pipeline_profile_measure_begin(void)
{
    return DWT_get_count();
}

static uint32_t pipeline_profile_measure_end(uint32_t start_count)
{
    return DWT_count_to_us((uint32_t) (DWT_get_count() - start_count));
}

static void pipeline_profile_print_every(const pipeline_profile_t * p_profile)
{
    static uint32_t s_frame_count = 0U;

    s_frame_count++;
    if ((1U == s_frame_count) || (0U == (s_frame_count % PIPELINE_PROFILE_PRINT_INTERVAL)))
    {
        uint32_t fps_x100 = (p_profile->total_us > 0U) ? (100000000U / p_profile->total_us) : 0U;
        uint32_t fps_int   = fps_x100 / 100U;
        uint32_t fps_frac  = fps_x100 % 100U;

        printf("[PIPE] frame=%lu fps=%lu.%02lu total=%lu us ceu_wait=%lu us ceu_kick=%lu us vsync=%lu us blit=%lu us draw=%lu us pre=%lu us model=%lu us post=%lu us center=%lu us\r\n",
               (unsigned long) s_frame_count,
               (unsigned long) fps_int,
               (unsigned long) fps_frac,
               (unsigned long) p_profile->total_us,
               (unsigned long) p_profile->ceu_us,
               (unsigned long) p_profile->ceu_kick_us,
               (unsigned long) p_profile->vsync_wait_us,
               (unsigned long) p_profile->blit_us,
               (unsigned long) p_profile->draw_us,
               (unsigned long) p_profile->preprocess_us,
               (unsigned long) p_profile->model_us,
               (unsigned long) p_profile->post_us,
               (unsigned long) p_profile->center_us);
    }
}

void g_timer_servo_tick_callback(timer_callback_args_t *p_args)
{
    FSP_PARAMETER_NOT_USED(p_args);
    RobotArm_Update();
}

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    // SDRAM is initialized in warmstart by R_BSP_SdramInit(true).
    /* TODO: add your own code here */
    uint32_t  ceu_used;
    fsp_err_t err = FSP_SUCCESS;
    fsp_err_t ioport_err = R_IOPORT_Open(&g_ioport_ctrl, &g_bsp_pin_cfg1);
    if (FSP_ERR_ALREADY_OPEN == ioport_err)
    {
        ioport_err = R_IOPORT_PinsCfg(&g_ioport_ctrl, &g_bsp_pin_cfg1);
    }

    uart9_Init();
    printf("test\r\n");

    RobotArm_Init();
    err = g_timer_servo_tick.p_api->open(g_timer_servo_tick.p_ctrl, g_timer_servo_tick.p_cfg);
    if (FSP_SUCCESS != err)
    {
        printf("Servo tick timer open failed: %d\r\n", (int) err);
    }
    else
    {
        err = g_timer_servo_tick.p_api->start(g_timer_servo_tick.p_ctrl);
        if (FSP_SUCCESS != err)
        {
            printf("Servo tick timer start failed: %d\r\n", (int) err);
        }
    }

    graphics_init(); // Initialize Dave2D graphics engine.
    mipi_dsi_entry();
    st7123_touch_irq_init();
    ui_control_init(); // 手绘双界面 UI：品牌条 + banner + MODE/START 按钮
    __DSB();

    R_IIC_MASTER_Open(&g_i2c_master0_ctrl, &g_i2c_master0_cfg); // I2C for camera and touch panel.
    ui_control_draw_boot_text("CAMERA INIT");   /* 上电提示：OV5640 配置 ~1s */
    ov5640_init();
    ov5640_config_dvp_vga_rgb565_15fps();
//    ov5640_set_output_format(OV5640_OUTPUT_FORMAT_RGB565);
//    ov5640_set_output_size(VGA_WIDTH,VGA_HEIGHT);
    ov5640_auto_focus_init();
    ov5640_set_exposure_level(OV5640_EXPOSURE_LEVEL_5);

    ceu_init(g_image_vga_sdram[0], VGA_WIDTH, VGA_HEIGHT);
    /* ===== NPU init ===== */

    ui_control_draw_boot_text("NPU INIT");      /* 上电提示：Ethos-U55 初始化 */
    err  = RM_ETHOSU_Open(&g_rm_ethosu0_ctrl, &g_rm_ethosu0_cfg);
    if (FSP_SUCCESS != err)
    {
        printf("NPU Ethos-U55 open failed: %d\r\n", err);
    }
    else
    {
        printf("NPU Ethos-U55 initialized successfully\r\n");
    }

    /*
     * 当前 AI 主链路：
     * 1) CEU 采集到双缓冲
     * 2) 对最新完整帧做预处理
     * 3) �?TFLite int8 + Ethos-U55
     * 4) 后处理后保留检测结果，画框和中心偏移给机械臂用
     */
    ai_letterbox_info_t letterbox_info;
    ai_detection_t detections_work[AI_POST_MAX_DETECT];
    ai_detection_t detections_committed[AI_POST_MAX_DETECT];
    uint32_t num_detections_work = 0U;
    uint32_t num_detections_committed = 0U;
    uint32_t detection_hold_frames = 0U;
    uint8_t * p_camera_buffers[2] = { g_image_vga_sdram[0], g_image_vga_sdram[1] };
    uint32_t frame_index_display = 0U;
    uint32_t frame_index_capture = 1U;
    uint32_t s_no_frame_ticks = 0U;   /* 连续无相机帧轮数（~16.7ms/轮，断流检测） */
    uint32_t s_prev_frame_end_cyc = 0U;  /* 上一帧处理完成时的 DWT 周期（真实帧率测量） */
    int8_t *p_model_input = GetModelInputPtr_serving_default_images_0();
    int8_t *p_model_p4    = GetModelOutputPtr_PartitionedCall_0_70298();
    int8_t *p_model_p5    = GetModelOutputPtr_PartitionedCall_1_70299();
    printf("[MODEL] profiling enabled on UART9; backend=tflite-int8(cpu+npu)\r\n");
    DWT_init();
    ui_control_draw_boot_text("READY");         /* 上电提示：就绪（首帧相机画面即将覆盖） */
    /* 上电不启动抓取：等待用户在屏幕上按 POWER 开关后，由 ui_control 启动
     * HarvestTask_Init()。 */
    prepare_camera_capture_buffer(p_camera_buffers[frame_index_display]);
    err = ceu_capture_start(p_camera_buffers[frame_index_display]);
    if (FSP_SUCCESS != err)
    {
        printf("CEU initial capture start failed: %d\r\n", (int) err);
        return;
    }

    err = ceu_capture_wait(&ceu_used, 2000U);
    if (FSP_SUCCESS != err)
    {
        printf("CEU initial capture wait failed: %d\r\n", (int) err);
        return;
    }

    /*
     * Pipeline:
     * 1) Display/process the latest completed frame.
     * 2) Capture the next frame into the other SDRAM buffer in parallel.
     */
    while(1)
    {
          /* 高频触摸 + UI 状态机（摇杆/按钮）：每轮执行，vsync 60Hz 节奏，
           * 不受相机 8fps 限制——遥控操作流畅跟手 */
          st7123_touch_irq_print_task();
          ui_control_service();

          /* 非阻塞轮询相机帧完成（CEU 回调置 g_capture_ready） */
          if (g_capture_ready)
          {
              g_capture_ready = false;
              s_no_frame_ticks = 0U;

          pipeline_profile_t pipe_profile = {0};
          uint32_t stage_start = 0U;
          /* 帧周期计时：loop_start = 上一帧处理完成时刻 → total 含帧等待，
           * fps 打印为真实画面帧率（相机硬件 ~8fps），而非处理吞吐 */
          uint32_t now_cyc = DWT_get_count();
          uint32_t loop_start = (0U != s_prev_frame_end_cyc) ? s_prev_frame_end_cyc : now_cyc;
          s_prev_frame_end_cyc = now_cyc;
          const model_profile_t * p_model_profile = NULL;
          uint8_t * p_display_frame = p_camera_buffers[frame_index_display];
          uint8_t * p_capture_frame = p_camera_buffers[frame_index_capture];

          /* 先 kick 下一帧采集（与当前帧的 blit/AI 处理重叠，保持 8fps 流水线） */
          frame_index_display ^= 1U;
          frame_index_capture ^= 1U;
          prepare_camera_capture_buffer(p_capture_frame);
          err = ceu_capture_start(p_capture_frame);
          if (FSP_SUCCESS != err)
          {
              printf("CEU capture start failed: %d\r\n", (int) err);
              R_BSP_SoftwareDelay(500, BSP_DELAY_UNITS_MILLISECONDS);
              continue;
          }

          /* Dave2D hardware scale: 640x480 -> camera window on display.
           * AUTO: full 480x640; REMOTE: 480x360 top area. */
          int cam_x, cam_y, cam_w, cam_h;
          bool is_auto = ui_control_get_camera_rect(&cam_x, &cam_y, &cam_w, &cam_h);
          stage_start = pipeline_profile_measure_begin();
          graphics_blit_scale(p_display_frame, 640, 480,
                  (uint8_t *) gp_frame_buffer + (uint32_t) cam_y * g_hstride * 2U,
                              cam_w, cam_h,
                              (int)g_hstride);
          pipe_profile.blit_us = pipeline_profile_measure_end(stage_start);

          /* 画框使用已提交结果；仅 AUTO 界面画（REMOTE 画面缩小，坐标系不匹配） */
          stage_start = pipeline_profile_measure_begin();
          if (is_auto)
          {
              ai_draw_detections(detections_committed, num_detections_committed);
          }
          ui_control_set_detection_count(num_detections_committed);
          pipe_profile.draw_us = pipeline_profile_measure_end(stage_start);
          __DSB();

          /* blit 覆盖了品牌条/按钮：立即重绘浮层（覆盖瞬间恢复，防闪烁） */
          ui_control_draw_overlay();

          /* 品牌条只绘制一次（ui_control_init 时）。以下一次性诊断验证
           * blit 是否越界污染金字区（y0-28）：x240/y10 为品牌条深蓝背景，
           * 若被相机帧覆盖则打印 CORRUPTED。 */
          if (is_auto)
          {
              static bool s_brand_checked = false;
              if (!s_brand_checked)
              {
                  s_brand_checked = true;
                  uint16_t * p_fb = (uint16_t *) gp_frame_buffer;
                  uint16_t v = p_fb[(uint32_t) 10 * (uint32_t) g_hstride + 240U];
                  if ((0x0907U == v) || (0xFBE0U == v))
                  {
                      printf("[BRAND] OK, untouched by blit (0x%04X)\r\n", (unsigned) v);
                  }
                  else
                  {
                      printf("[BRAND] CORRUPTED by blit! pixel=0x%04X\r\n", (unsigned) v);
                  }
              }
          }

          /* AI 推理仅 AUTO 模式执行（REMOTE 跳过，保证摇杆响应流畅） */
          if (is_auto)
          {
              stage_start = pipeline_profile_measure_begin();
              ai_preprocess_rgb565(p_display_frame, VGA_WIDTH, VGA_HEIGHT,
                                   p_model_input, &letterbox_info);
              pipe_profile.preprocess_us = pipeline_profile_measure_end(stage_start);

              p_model_profile = RunModelProfiled(false);
              if (NULL != p_model_profile)
              {
                  pipe_profile.model_us = p_model_profile->total_us;
                  pipe_profile.cpu_us   = p_model_profile->cpu_us;
                  pipe_profile.npu_us   = p_model_profile->npu_us;
              }

              num_detections_work = 0U;
              stage_start = pipeline_profile_measure_begin();
              ai_postprocess(p_model_p4, p_model_p5,
                             &letterbox_info, detections_work, AI_POST_MAX_DETECT,
                             &num_detections_work);
              pipe_profile.post_us = pipeline_profile_measure_end(stage_start);

              if (num_detections_work > 0U)
              {
                  memcpy(detections_committed,
                         detections_work,
                         num_detections_work * sizeof(ai_detection_t));
                  num_detections_committed = num_detections_work;
                  detection_hold_frames = AI_RESULT_HOLD_FRAMES;
              }
              else if (detection_hold_frames > 0U)
              {
                  detection_hold_frames--;
              }
              else
              {
                  num_detections_committed = 0U;
              }
          }

          /* 中心偏移只看当前稳定结果；仅 AUTO + POWER 时驱动抓取流程 */
          stage_start = pipeline_profile_measure_begin();
          if ((UI_MODE_AUTO == ui_control_get_mode()) &&
              (UI_POWER_ON == ui_control_get_power()))
          {
              HarvestTask_Service(detections_committed, num_detections_committed);
          }
          pipe_profile.center_us = pipeline_profile_measure_end(stage_start);

          pipe_profile.total_us = pipeline_profile_measure_end(loop_start);
          pipeline_profile_print_every(&pipe_profile);
          }
          else if (++s_no_frame_ticks >= 120U)   /* ~2s 无帧：CEU 断流自愈（换同步配置 + 重开） */
          {
              s_no_frame_ticks = 0U;
              ceu_recover();
              /* reopen 后 CEU 空闲：直接重新 kick 当前采集缓冲 */
              prepare_camera_capture_buffer(p_camera_buffers[frame_index_capture]);
              err = ceu_capture_start(p_camera_buffers[frame_index_capture]);
              if (FSP_SUCCESS != err)
              {
                  printf("CEU recover kick failed: %d\r\n", (int) err);
              }
          }

          /* UI 浮层每轮重绘（60Hz 跟手，与相机帧率解耦；相机断流时 UI 不冻结） */
          ui_control_draw_overlay();
          __DSB();

          /* 60Hz 节奏：等待 GLCDC vsync（无相机帧时也等，保持触摸采样稳定） */
          g_vsync_flag = RESET_FLAG;
          wait_vsync_with_timeout(1000U);
    }

    /* Wake up 2nd core if this is first core and we are inside a multicore project. */
#if (0 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && !BSP_TZ_NONSECURE_BUILD

#if BSP_TZ_SECURE_BUILD
    /* Take semaphore so 2nd core can clear it */
    R_BSP_IpcSemaphoreTake(&g_core_start_semaphore);
#endif

    R_BSP_SecondaryCoreStart();

#if BSP_TZ_SECURE_BUILD
    /* Wait for 2nd core to start and clear semaphore */
    while(FSP_ERR_IN_USE == R_BSP_IpcSemaphoreTake(&g_core_start_semaphore))
    {
        ;
    }
#endif
#endif

#if (1 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
    /* Signal to 1st core that 2nd core has started */
    R_BSP_IpcSemaphoreGive(&g_core_start_semaphore);
#endif

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
