#include "hal_data.h"
#include "Uart9_Debug.h"
#include "board_sdram.h"
#include "mipi_dsi_ep.h"
#include "Stepping_Motor.h"
#include "stdio.h"
#include "ov5640.h"
#include "ceu.h"
#include "graphics.h"

#if (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
bsp_ipc_semaphore_handle_t g_core_start_semaphore =
{
    .semaphore_num = 0
};
#endif

uint8_t g_image_vga_sram [ VGA_WIDTH * VGA_HEIGHT * RGB565_BYTE_PER_PIXEL ] __attribute__((aligned(32)));
//VGA = 640*480
//uint8_t g_image_vga_sram [ 480 * 480 * RGB565_BYTE_PER_PIXEL ] ;

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    //SDRAM 已在 warmstart 中由 R_BSP_SdramInit(true) 初始化，此处无需重复
    /* TODO: add your own code here */
    uint32_t  ceu_used;
    fsp_err_t err = FSP_SUCCESS;
    fsp_err_t ioport_err = R_IOPORT_Open(&g_ioport_ctrl, &g_bsp_pin_cfg1);
    if (FSP_ERR_ALREADY_OPEN == ioport_err)
    {
        ioport_err = R_IOPORT_PinsCfg(&g_ioport_ctrl, &g_bsp_pin_cfg1);
    }

    uart9_Init();
    printf("test\r\n");
    R_IIC_MASTER_Open(&g_i2c_master0_ctrl, &g_i2c_master0_cfg); //I2C（给摄像头和触摸屏用）


    ov5640_init();
    ov5640_set_output_format(OV5640_OUTPUT_FORMAT_RGB565);
    ov5640_auto_focus_init();
    ov5640_set_output_size(VGA_WIDTH,VGA_HEIGHT);
    ov5640_set_exposure_level(OV5640_EXPOSURE_LEVEL_8);

    ceu_init(g_image_vga_sram, VGA_WIDTH, VGA_HEIGHT);
    graphics_init(); //Dave2D 图形引擎初始化
    mipi_dsi_entry();
    gp_frame_buffer = gp_single_buffer;
    while(1)
    {
           err = ceu_capture_one_frame(g_image_vga_sram, VGA_WIDTH, VGA_HEIGHT, &ceu_used);
           if (FSP_SUCCESS != err)
           {
               printf("CEU operation failed: %d, waited=%lu ms\r\n", err, (unsigned long) ceu_used);
               R_BSP_SoftwareDelay(500, BSP_DELAY_UNITS_MILLISECONDS);
               continue;
           }
    }

    /* Wake up 2nd core if this is first core and we are inside a multicore project. */
#if (0 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && !BSP_TZ_NONSECURE_BUILD

#if BSP_TZ_SECURE_BUILD
    /* Take semaphore so 2nd core can clear it */
    R_BSP_IpcSemaphoreTake(&g_core_start_semaphore);
#endif

    R_BSP_SecondaryCoreStart();

#if BSP_TZ_SECURE_BUILD
    /* Wait for 2nd core to start and clear semaphore */
    while(FSP_ERR_IN_USE == R_BSP_IpcSemaphoreTake(&g_core_start_semaphore))
    {
        ;
    }
#endif
#endif

#if (1 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
    /* Signal to 1st core that 2nd core has started */
    R_BSP_IpcSemaphoreGive(&g_core_start_semaphore);
#endif

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
